# Servidor
server.port=8081

# Nombre de la aplicación
spring.application.name=ms-inventario

# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/smartlogix_inventario
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers
management.endpoint.health.show-details=always

# Resilience4j Circuit Breaker
resilience4j.circuitbreaker.instances.inventarioService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.inventarioService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.inventarioService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventarioService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.inventarioService.permittedNumberOfCallsInHalfOpenState=3
