server.port=8082
spring.application.name=ms-pedidos

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/smartlogix_pedidos?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# URL del ms-inventario (para consultar stock)
smartlogix.inventario.url=http://localhost:8081

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
management.endpoints.web.exposure.include=health,info,metrics
